create extension if not exists "pgcrypto";
create table businesses(id uuid primary key default gen_random_uuid(),name text not null,owner_name text,currency text not null default 'MYR',timezone text not null default 'Asia/Kuala_Lumpur',created_at timestamptz default now());
create table business_members(business_id uuid references businesses(id) on delete cascade,user_id uuid not null,role text not null default 'owner',primary key(business_id,user_id));
create table products(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text not null,category text,selling_price numeric(12,2) default 0,ingredient_cost numeric(12,2) default 0,packaging_cost numeric(12,2) default 0,other_cost numeric(12,2) default 0,active boolean default true,created_at timestamptz default now());
create table customers(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text not null,phone text,email text,notes text,created_at timestamptz default now());
create table orders(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,customer_id uuid references customers(id) on delete set null,order_date date default current_date,required_date date,required_time time,status text default 'New',payment_status text default 'Unpaid',total numeric(12,2) default 0,deposit numeric(12,2) default 0,notes text,created_at timestamptz default now());
create table order_items(id uuid primary key default gen_random_uuid(),order_id uuid references orders(id) on delete cascade,product_id uuid references products(id) on delete set null,quantity numeric(12,2) not null,unit_price numeric(12,2) not null);
create table inventory_items(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text not null,category text,quantity numeric(12,3) default 0,unit text default 'unit',reorder_level numeric(12,3) default 0,unit_cost numeric(12,2) default 0,supplier text,expiry_date date,created_at timestamptz default now());
create table inventory_transactions(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,inventory_item_id uuid references inventory_items(id) on delete cascade,transaction_type text not null,quantity numeric(12,3) not null,transaction_date date default current_date,notes text);
create table content_items(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,platform text not null,content_type text not null,product_id uuid references products(id) on delete set null,idea text,status text default 'Idea',published_url text,views integer,likes integer,comments integer,shares integer,saves integer,posted_at date,created_at timestamptz default now());
create table tasks(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,title text not null,description text,category text,priority text default 'Medium',estimated_minutes integer,scheduled_date date,scheduled_time time,status text default 'Not Started',source text default 'Manual',completed_at timestamptz,created_at timestamptz default now());
create table schedule_blocks(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,day_of_week integer not null,start_time time not null,end_time time not null,title text not null,category text,active boolean default true);
create table goals(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id) on delete cascade,name text not null,metric text not null,target numeric(12,2) not null,start_date date not null,end_date date not null,created_at timestamptz default now());
create index idx_orders_business_date on orders(business_id,order_date);
create index idx_tasks_business_date on tasks(business_id,scheduled_date);
create index idx_products_business on products(business_id);
create index idx_inventory_business on inventory_items(business_id);
create index idx_content_business_date on content_items(business_id,posted_at);
-- Enable RLS and add business-membership policies before production use.
